In [1]:
import numpy as np

<h3>1.) Write a NumPy program to compute the multiplication of two given matrixes.</h3>

In [2]:
a = [[1, 0], [0, 1]]
b = [[1, 2], [3, 4]]

#write your answers here
np.matmul(a,b)

array([[1, 2],
       [3, 4]])

<h3>2.) How to get the n largest values of an array?</h3>

In [3]:
Z = np.array([0,1,2,3,4,5,6,10,23])
np.random.shuffle(Z)
n = 5

#write your answers here
list(Z[np.argsort(Z)[-n:]]) # argsort converts to sorted index, and then split list backwards (or forward with n-1)

[4, 5, 6, 10, 23]

<h3>3.) How to find the most frequent value in an array?</h3>

In [4]:
Z = np.random.randint(0,10,50)

#write your answers here
print(Z)
np.bincount(Z).argmax() # count occurences and then return number w max occurences

[7 8 9 3 6 2 5 0 2 8 1 0 3 1 6 3 9 7 3 5 7 4 1 5 8 9 8 2 6 3 9 3 6 0 7 6 5
 7 1 4 5 7 9 1 0 9 8 4 5 9]


9

<h3>4.) How to extract items that satisfy a given condition from 1D array? </h3>

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#find the odd numbers in the numpy array
#output must be [1,3,5,7,9]

In [6]:
#write your answers here
list(arr[arr % 2 == 1])

[1, 3, 5, 7, 9]

<h3>5.) How to reshape an array? </h3>

Reshape
```python
arr = [0 1 2 3 4 5 6 7 8 9] to [[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]]
```

In [7]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#write your answers here
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h3>6.) Stacking NumPy Arrays Vertically </h3>
Stack the following numpy array:

```python
a = [[0 1 2 3 4]
     [5 6 7 8 9]] 
b = [[1 1 1 1 1]
     [1 1 1 1 1]]
to 
stacked_arr = [[0, 1, 2, 3, 4]
               [5, 6, 7, 8, 9]
               [1, 1, 1, 1, 1]
               [1, 1, 1, 1, 1]]
```

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [10]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
#write your answers here
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<h3>7.) How to convert a multidimensional into a flat 1d array? </h3>

In [13]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [14]:
array_of_arrays = np.array([arr1, arr2, arr3])
print(array_of_arrays)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


convert into array_of_arrays into [0,1,2,3,4,5,6,7,8,9]

In [15]:
#write your answers here
list(np.hstack([arr1,arr2,arr3]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

<h3>8.) How to rank items in a multidimensional array using numpy? </h3>

In [16]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [17]:
#write your answers here
# not the best solution but it works

tmp = a.argsort() # gets index pos
rank = tmp.argsort() # sorts index pos
rank

array([[2, 1, 3, 0, 4],
       [3, 4, 1, 2, 0]])

<h3>9.) How to swap two columns in a 2d numpy array?</h3>

Swap columns 1 and 2 in array ```arr```

In [18]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#write your answers here
tmp = np.copy(arr[:,0]) # duplicate array
arr[:,0] = arr[:,1]
arr[:,1] = tmp

arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

<h3>10.) How to swap two columns in a 2d numpy array?</h3>

Reverse the rows in array ```arr``` from 
```python
arr = [[0 1 2]
       [3 4 5]
       [6 7 8]]
to 
[[6, 7, 8],
 [3, 4, 5],
 [0, 1, 2]]

```

In [20]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#write your answers here
tmp = np.copy(arr[0,:])
arr[0,:] = arr[2,:]
arr[2,:] = tmp

arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])